import Head from 'next/head'
import Image from 'next/image'

import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

import TodoList from '../components/TodoList';

import { fetchTodos } from "../storage/slices/todos";
import { RootState } from "../storage";

import styles from '../styles/Home.module.css'


export default function Home() {
  const todos = useSelector((state: RootState) => state.todos.items);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(fetchTodos());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h2 className={styles.subtitle}>
          + <a href="https://www.typescriptlang.org/">TS</a>
          &nbsp;+ <a href="https://github.com/axios/axios">Axios</a>
          &nbsp;+ <a href="https://redux-toolkit.js.org/">RTK</a>
        </h2>
      </main>

      <TodoList todos={todos} />
    </div>
  )
}
